Repository tensorflow/cleverhans, pull requests merged in 2018-07, with the labels that each got.

#423 Add defense sub-framework.
  cleverhans/attacks.py
  cleverhans/attacks_tf.py
  cleverhans/loss.py
  cleverhans/model.py
  cleverhans/utils_keras.py
  cleverhans/utils_tf.py
  cleverhans_tutorials/mnist_blackbox.py
  cleverhans_tutorials/mnist_tutorial_cw.py
  cleverhans_tutorials/mnist_tutorial_jsma.py
  cleverhans_tutorials/mnist_tutorial_keras_tf.py
  cleverhans_tutorials/mnist_tutorial_tf.py
  cleverhans_tutorials/tutorial_models.py
  examples/ex_cifar10_tf.py
  examples/facenet_adversarial_faces/facenet_fgsm.py
  examples/imagenet_featadvs/attack_model_featadv.py
  examples/imagenet_featadvs/model.py
  examples/linear_extrapolation_plot_example.py
  examples/madry_lab_challenges/cifar10/madry_cifar10_model.py
  examples/madry_lab_challenges/mnist/madry_mnist_model.py
  examples/multigpu_advtrain/make_model.py
  examples/multigpu_advtrain/model.py
  examples/multigpu_advtrain/resnet_tf.py
  examples/multigpu_advtrain/run_multigpu.py
  examples/multigpu_advtrain/trainer.py
  examples/robust_vision_benchmark/cleverhans_attack_example/utils.py
  tests_tf/test_attacks.py
  tests_tf/test_defenses.py
  tests_tf/test_mnist_blackbox.py
  tests_tf/test_mnist_tutorial_tf.py
  tests_tf/test_model.py
  tests_tf/test_utils.py
  tests_tf/test_utils_keras.py
Labels: waiting for contributor

#447 Depreciation messages
  cleverhans/attacks.py
  cleverhans/attacks_tf.py
  cleverhans/compat.py
  cleverhans/utils_tf.py
  cleverhans_tutorials/mnist_tutorial_pytorch.py
Labels: waiting for contributor

#441 Transition to tf.while_loops for iterative attacks
  cleverhans/attacks.py
Labels: waiting for contributor

#445 Fixing the tutorial for non-MNIST datasets
  cleverhans_tutorials/mnist_blackbox.py
  cleverhans_tutorials/mnist_tutorial_cw.py
  cleverhans_tutorials/mnist_tutorial_jsma.py
  cleverhans_tutorials/mnist_tutorial_keras_tf.py
  cleverhans_tutorials/mnist_tutorial_tf.py
Labels: waiting for contributor

#449 Jacobian Augmentation SpeedUp
  cleverhans/attacks_tf.py
  cleverhans_tutorials/mnist_blackbox.py
Labels: waiting for reviewer

#442 Add handling for training keras models in mnist_blackbox tutorial
  examples/mnist_blackbox_keras.py
Labels: waiting for contributor

#459 Allow omitted nb_classes parameter in KerasModelWrapper()
  cleverhans/model.py
  cleverhans/utils_keras.py
  cleverhans_tutorials/mnist_tutorial_keras_tf.py
  tests_tf/test_utils.py
  tests_tf/test_utils_keras.py
Labels: waiting for reviewer

#464 Bug fix in SPSA attack
  cleverhans/attacks.py
Labels: waiting for travis
